id: I2B1D1774
legacy_id: P008267
ocr_import_info:
  bdrc_scan_id: W8LS17181
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T08:47:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:44:08.699570+00:00'
last_modified: 2022-09-04 11:44:13.427054
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17181
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17181
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསོལ་འདེབས་ཞལ་མཐོང་མ་དང་སེར་བ་ལམ་བསྒྱུར།
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.642222935048664
  ocr_word_median_confidence_index: 0.6899999976158142
quality: null
bases:
  I8LS17192:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17192
      total_pages: 48
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17192.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.642222935048664
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
