id: P008267
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 19:21:06.667409
source_metadata:
  id: bdr:W8LS17181
  title: གསོལ་འདེབས་ཞལ་མཐོང་མ་དང་སེར་བ་ལམ་བསྒྱུར།
  author: ''
  volumes:
    c0f0b56baf304b83af518530baee2beb:
      image_group_id: I8LS17192
      title: ''
      volume_number: 1
      total_pages: 48
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
